### ISSUE TITLE
Ошибка при определении пути к платформе

### ISSUE THREAD

**Issue by realMaxA** [oscript-library/v8runner#10]
На версии v8runner 0.5.0 при определении пути к платформе в среде windows возникает ошибка:

```
Ошибка в строке: 566 / Ошибка определения версии платформы. Файл <C:\Program Files\1cv8\8.3.8.2054\bin\1cv8.exe> не существует
```

Дело в том, что на компьютере не установлен 64-х битный клиент, есть только 64-х битный сервер.

**Comment by nixel2007** [comment]
Просьба проверить на 0.5.1

/cc @artbear

**Comment by realMaxA** [comment]
На 0.5.1 ситуация не изменилась

**Comment by nixel2007** [comment]
@realMaxA можно полный лог? Желательно с включенными отладочными сообщениями.

**Comment by artbear** [comment]
>Дело в том, что на компьютере не установлен 64-х битный клиент, есть только 64-х битный сервер.

@realMaxA Если на машине есть только сервер, то клиентских приложений 1cv8.exe и 1cv8c.exe на машине просто нет.
И сообщение об ошибке логично.

Какое поведение `v8runner` ожидается?

**Comment by artbear** [comment]
Или установлен 64-разрядный сервер и 32-разрядный клиент?

**Comment by artbear** [comment]
ИМХО тут проблема с нахождением и использованием переменной `ПодтвержденныйПуть` :(
Эта переменная почему-то фиксирована, хотя мы используем массив каталогов (МассивФайлов) для выбора `правильного` каталога

**Comment by realMaxA** [comment]
Да, всё правильно,

> установлен 64-разрядный сервер и 32-разрядный клиент

**Comment by realMaxA** [comment]
Для 8.3.8.2054 нет 64-разрядного клиента для windows

Лог:
[log.txt](https://github.com/oscript-library/v8runner/files/695913/log.txt)

**Comment by artbear** [comment]
https://github.com/oscript-library/v8runner/issues/10 ИМХО из-за моей ошибки

слегка недоисправил код :( [Строка](https://github.com/oscript-library/v8runner/commit/10036f059bc22438faa0dd27cf947a1590899af8#diff-a7019bb8a9cceee943a7487142549f7aR514)
Нужно было цикл делать по `МассивКаталогов1С`, а я оставил старый вариант `МассивФайлов` :(

все дальнейшие PR также неверны

**Comment by artbear** [comment]
Хотя код с `ВозможныйПуть` / `ПодтвержденныйПуть` внесен до моего исправления и он также неверен!
