### ISSUE TITLE
Как написать метод

### ISSUE THREAD

**Issue by testforgity** [oscript-library/v8runner#100]
И снова здравствуйте, как можно создать серверную базу, чуть-чуть не понимаю как все это оформить: хочу создать базу на адресе, допустим, 1.1.1.1\test_bdd (test_bdd - название бд), MSSQLServer как БД, сервак SQL - 2.2.2.2, пользователь сервака sa, пароль 123. Метод естественно СоздатьСервернуюБазу. просто как вот аргументы оформить не представляю нормально

**Comment by nixel2007** [comment]
https://github.com/oscript-library/v8runner/blob/master/src/v8runner.os#L1100-L1128

Первые три параметра - структуры, описывающие параметры 1С и СУБД. Нужно просто положить туда правильные свойства.
