### ISSUE TITLE
Автоопределение версии платформы (мВерсияПлатформы)

### ISSUE THREAD

**Issue by d-hurricane** [oscript-library/v8runner#109]
В модуле присутствует глобальная не экспортная переменная **мВерсияПлатформы,** которая активно участвует в проверке доступных ключей запуска 1С-приложения. Например, метод **ВыгрузитьКонфигурациюВФайлы** проверяет используется ключи "-update" и "-force" только при условии, что версия используемой платформы не ниже 8.3.10.

Проблема заключается в том, что при переходе на использование библиотеки **v8find** "потерялась" инициализация переменной **мВерсияПлатформы.** В результате принимается, что используемая платформа имеет версию "0.0.0.0", а следовательно некоторые методы модуля, опирающиеся на версию, всегда работают не "в полную силу".

К сожалению, моей компетенции не достаточно, чтобы устранить проблему. Для Windows можно было бы извлечь версию из полученного пути к исполняемому файлу 1С как имя каталога два разделителя назад от имени файла. Но как быть в случае с Linux - точно не знаю, могу лишь предполагать по старому исходному коду бибилотеки.

**Comment by artbear** [comment]
Исправлено в https://github.com/oscript-library/v8runner/pull/115
