### ISSUE TITLE
Добавить в лог отладки номер версии v8runner

### ISSUE THREAD

**Issue by realMaxA** [oscript-library/v8runner#11]
При просмотре логов работы v8runner нет возможности просто понять, какая версия выполняется.
Для этого помимо ключа соединения с базой, имени и пароля пользователя добавить информацию о версии.

**Comment by EvilBeaver** [comment]
А разве там пути полного к платформе не пишется?

**Comment by realMaxA** [comment]
Речь не о версии платформы, а о версии самого v8runner

**Comment by leemuar** [comment]
Для чего это нужно?

**Comment by realMaxA** [comment]
Я сейчас затрудняюсь вспомнить контекст, но, скорее всего, при использовании какой-нибудь использующей v8runner утилиты, вероятно vanessa-runner, в какой-то момент начала возникать ошибка. Для разбирательства с нею потребовалось выяснить версию используемого v8runner'а, что в логах не отражалось.

**Comment by EvilBeaver** [comment]
opm list

**Comment by leemuar** [comment]
@realMaxA, в данном случае мне кажется, что это выходит за рамки ответственности библиотеки. Это задача вызывающего скрипта: vanessa стоило бы перед началом своей работы записать в лог все версии используемых библиотек, используя, например, предложенный Андреем ```opm list```

**Comment by realMaxA** [comment]
Возможно. Я не настаиваю. issue я закрою.

С другой стороны мне не ясно, почему вывод версии библиотеки в log(!), в debug(!) режиме выходит за рамки ответственности библиотеки. (наверное я это так никогда и не узнаю :) -- на ответе не настаиваю)
