### ISSUE TITLE
ФорматОтчета и ТипОтчета https://github.com/oscript-library/v8runner/blob/dd1775b6df527af97f7724652c5f502b5d34e77d/src/v8runner.os#L1690

### ISSUE THREAD

**Issue by stanislavchernomiza** [oscript-library/v8runner#112]
Добрый день. Если я не ошибаюсь, то перепутаны местами при передачи параметров ФорматОтчета и ТипОтчета, вроде как должно быть наоборот (1689-1693) v8runner.os

**Comment by EvilBeaver** [comment]
Проще сделать пулреквест с предлагаемыми изменениями и его можно предметно обсудить

**Comment by stanislavchernomiza** [comment]
Добрый день. Сделал пулреквест.
