### ISSUE TITLE
Параметр -Server при обновлении конфигурации

### ISSUE THREAD

**Issue by LazarenkoA** [oscript-library/v8runner#114]
Тут второй параметр лучше б Ложь
https://github.com/oscript-library/v8runner/blob/dd1775b6df527af97f7724652c5f502b5d34e77d/src/v8runner.os#L849

пока он был истина у меня не обновлялось, выдавала ошибку :

> ОШИБКА - [oscript.lib.v8runner] - Получен ненулевой код возврата 1. Выполнение скрипта остановлено!
> КРИТИЧНАЯОШИБКА - [o.app.vanessa-runner] - {Модуль /usr/share/oscript/lib/vanessa-runner/src/Классы/КомандаЗагрузитьРасширениеИзФайла.os / Ошибка в строке: 71 / {Модуль /usr/share/oscript/lib/vanessa-runner/oscript_modules/v8runner/src/v8runner.os / Ошибка в строке: 1354 / Ошибка в параметрах командной строки.

Причем раньше я тоже натыкался на эту странность, что с ключом -Server не работает (linux CentOS)

**Comment by EvilBeaver** [comment]
Можете расследовать чуть глубже? Почему ошибка выдавалась, на что влияет этот "второй параметр"?

**Comment by LazarenkoA** [comment]
> Можете расследовать чуть глубже? Почему ошибка выдавалась, на что влияет этот "второй параметр"?

Я ж написал, с этим параметром добавляется ключ -server, а ошибку уже возвращает 1с, почему она ее возвращает не могу знать, только если в тех поддержку им писать

**Comment by EvilBeaver** [comment]
> только если в тех поддержку им писать

Звучит, как невыполнимая задача. Почему вам кажется, что кто-то из авторов пакета v8runner с этим лучше справится?

**Comment by LazarenkoA** [comment]
Вопрос в том, зачем делать что бы был ключ server, если показаний для этого нет, уберите его, сейчас то он по дефолту установлен

**Comment by nixel2007** [comment]
База файловая или клиент-серверная?

**Comment by artbear** [comment]
@LazarenkoA нужно было всего лишь указать более точно проблему - проблема же не в загрузке конфигурации, а при загрузке расширения. Решилось бы быстрее. Подсказка-то верная была.

проблема исправлена в https://github.com/oscript-library/v8runner/pull/128
