### ISSUE TITLE
Добавить функцию "КаталогКонфигурационныхФайлов1С"

### ISSUE THREAD

**Issue by johnnyshut** [oscript-library/v8runner#116]
Чтобы была возможность переходить в "C:\Program Files\1cv8\conf". 
Функционал: Получение Пути к каталогу с конфигом платформы 1С

Я хочу менять файлы внутри
Чтобы программно включать ТЖ и править остальные файлы программно.

**Comment by johnnyshut** [comment]
Переименовал функцию в "КаталогКонфигурационныхФайлов1С"

**Comment by artbear** [comment]
Выполнено.
