### ISSUE TITLE
call runner loadext  не работает с параметром --updatedb 

### ISSUE THREAD

**Issue by kwazispb** [oscript-library/v8runner#118]
call runner loadext --extension Расширение --updatedb --file="./build/1cv8.cfe" не работает
Расширение загружается, но на следущем шаге (обновление БД) падает с ошибкой:
Ошибка в параметрах командной строки.

Приходится делать так: Сначала loadext (без ключа updatedb), потом запускать updateext

**Comment by artbear** [comment]
исправлено в https://github.com/oscript-library/v8runner/pull/128
