### ISSUE TITLE
Вывод в комментариях гиперссылок для отчета хранилища 

### ISSUE THREAD

**Issue by abirambul** [oscript-library/v8runner#122]
Сейчас в отчете хранилища гиперссылка выводится в обрезанном виде.

Вместо "http://https://github.com/oscript-library/v8runner/issues/new" в отчете будет выведено "http:".

В 8.3.17 добавлен ключ `-IncludeCommentLinesWithDoubleSlash` для `/ConfigurationRepositoryReport` исправляющий такое поведение.

**Comment by abirambul** [comment]
https://github.com/oscript-library/gitsync/issues/162

**Comment by artbear** [comment]
выполнено. уже в релизе
