### ISSUE TITLE
Не работает метод ОбновитьКонфигурациюБазыДанных для Расширений

### ISSUE THREAD

**Issue by mors1eska** [oscript-library/v8runner#125]
Пробую вызвать ОбновитьКонфигурациюБазыДанных для расширения и обновление не отрабатывает.
На сколько я по коду понял, отличие обновление БД от обновление БД Расширения сейчас только добавлением команды Extension

```
Если ЗначениеЗаполнено(ИмяРасширения) Тогда
		ПараметрыСвязиСБазой.Добавить("-Extension " + ИмяРасширения);
КонецЕсли;
```

Но командная строка которая получается у меня не отрабатывает (если просто в CMD ее писать)

`1cv8.exe DESIGNER /IBConnectionString "Srvr=13.0.0.22:1941;Ref=franunf" /Out "C:\Users\mors\AppData\Local\Temp\jp1pikkb.np4.txt" /N"***" /P"***" /UC"update" /UpdateDBCfg -Dynamic -Server -Extension пр_Расширение
`

Если убрать часть параметров, то все работает

`1cv8.exe DESIGNER /IBConnectionString "Srvr=13.0.0.22:1941;Ref=franunf" /Out "C:\Users\mors\AppData\Local\Temp\jp1pikkb.np4.txt" /N"***" /P"***" /UC"update" /UpdateDBCfg -Extension пр_Расширение`

То есть требуется убрать параметры -Dynamic -Server.

Это я что-то не так делаю? Или требуется переписать процедуру?

**Comment by EvilBeaver** [comment]
Скорее всего, вы наткнулись на особенности платформы и требуется либо переписать процедуру, либо добавить еще одну. Подозреваю, что флаг -Dynamic (запрет динамического обновления) несовместим с расширениями (которые по природе своей динамические)

**Comment by mors1eska** [comment]
Добрый, а мой вариант решения не подходит?

**Comment by artbear** [comment]
В https://github.com/vanessa-opensource/vanessa-runner/issues/400 автор @KrapivinAndrey пишет:
>Экспериментами выяснил, что проблема в параметре -Server при обновлении базы. Без него расширение загружаются и обновляются.

т.е. влияет только флаг -Server, а  -Dynamic не влияет.

mors1eska что скажешь?

**Comment by mors1eska** [comment]
> В [vanessa-opensource/vanessa-runner#400](https://github.com/vanessa-opensource/vanessa-runner/issues/400) автор @KrapivinAndrey пишет:
> 
> > Экспериментами выяснил, что проблема в параметре -Server при обновлении базы. Без него расширение загружаются и обновляются.
> 
> т.е. влияет только флаг -Server, а -Dynamic не влияет.
> 
> mors1eska что скажешь?

как-то пропустил вопрос, извиняюсь.
Да, я тоже к этому пришел, влияет -Server
