### ISSUE TITLE
Процедуру ВыполнитьКоманду сделать Функцией

### ISSUE THREAD

**Issue by CT144** [oscript-library/v8runner#14]
Процедуру "ВыполнитьКоманду" сделать Функцией, возвращающей "КодВозврата" от функции "ЗапуститьИПодождать", что бы дать возможность анализировать вызывающему коду результат выполнения команды. При этом отменить выброс исключения при не нулевом коде возврата из "ЗапуститьИПодождать". Это нужно, например, при запуске обновления конфигурации, которое может по разным причинам завершиться с не нулевым кодом возврата. Это предложение в "чистом" виде, а для сохранения совместимости можно в параметры процедуры "ВыполнитьКоманду" добавить 2-ой параметр: КодВозврата=Неопределено, который и устанавливать в случае его задания.  
Или для полной "соовместимости" с текущей реализацией можно сделать так:
Процедура ВыполнитьКоманду(Знач Параметры, Результат = Неопределено) Экспорт
...
	КодВозврата = ЗапуститьИПодождать(Параметры);
	УстановитьВывод(ПрочитатьФайлИнформации());
	Если Результат = Неопределено Тогда
		Если КодВозврата <> 0 Тогда
			Лог.Ошибка("Получен ненулевой код возврата "+КодВозврата+". Выполнение скрипта остановлено!");
			ВызватьИсключение ВыводКоманды();
		Иначе
			Лог.Отладка("Код возврата равен 0");
		КонецЕсли;
	Иначе
		Результат = КодВозврата;
	КонецЕсли;

**Comment by nixel2007** [comment]
Полезное предложение, спасибо!

Не хотелось бы менять имеющееся апи (вызов исключения).

Можно подумать над таким вариантом -
* ВыполнитьКоманду становится функцией, возвращающей код возврата
* у УправлениеКонфигуратором добавляется метод а-ля "КидатьИсключениеПриПадении(Истина/Ложь) - значение по умолчанию - истина
* В ВыполнитьКоманду анализируется свойство мКидатьИсключениеПриПадении - если истина, тогда кидать.

Возможно параллельно стоит рассмотреть возможность перевода запуска на 1commands, если научить 1commands сразу писать в лог, а не скопом после полного выполнения команды (как идет сейчас).

**Comment by EvilBeaver** [comment]
Предложение Никиты нравится

**Comment by artbear** [comment]
>Возможно параллельно стоит рассмотреть возможность перевода запуска на 1commands, если научить 1commands сразу писать в лог, а не скопом после полного выполнения команды (как идет сейчас).

@nixel2007 С момента появления идеи выделения 1commands и в процессе реализации я подразумеваю подобный переход.
Например, есть ишуз https://github.com/artbear/1commands/issues/4 `Получение вывода команды, у которой есть отдельный лог-файл`, как раз для работы с Конфигуратором

По поводу "сразу писать в лог" - да, нужно добавить эту фичу.

**Comment by artbear** [comment]
Ну что, немедленный вывод добавлен https://github.com/artbear/1commands/issues/21

Реализую https://github.com/artbear/1commands/issues/4 и затем можно переводить v8runner на использование 1сщььфтвы, в котором хотелки из сабжа и многие другие уже реализованы.

**Comment by EvilBeaver** [comment]
Тут @pumbaEO в гиттере нашел проблему с 1commands. Если запускается GUI приложение (а в данном случае это как раз так), то читать у него потоки бесполезно. К тому же Поток.Прочитать() упадет. У конфигуратора нет потоков вывода, поэтому он и пишет в файлик Out.

При переходе на 1commands это надо учесть.

**Comment by artbear** [comment]
Спасибо за ваши комменты, но, мужчины, может быть, все-таки будем предыдущие комменты читать, а? :(

Я и в https://github.com/oscript-library/v8runner/issues/14#issuecomment-273207323 (17.01.17) я уже писал
>С момента появления идеи выделения 1commands и в процессе реализации я подразумеваю подобный переход.
Например, есть ишуз artbear/1commands#4 Получение вывода команды, у которой есть отдельный лог-файл, как раз для работы с Конфигуратором

И в https://github.com/oscript-library/v8runner/issues/14#issuecomment-281174494 (3 дня назад) также писал
>Реализую artbear/1commands#4 и затем можно переводить v8runner на использование 1commands, в котором хотелки из сабжа и многие другие уже реализованы.

**Comment by EvilBeaver** [comment]
Я просто напомнил про эту хрень. Женя недавно попытался запускать тонкий клиент коммандсом

**Comment by artbear** [comment]
выполнено в #50
