### ISSUE TITLE
ВыгрузитьИнформационнуюБазу - не найдена информационная база. В пути к базе есть кириллица

### ISSUE THREAD

**Issue by FreeJamesBrown** [oscript-library/v8runner#152]
Добрый день! Не знаю, было ли, но вот какую ошибку нашел (может это и не ошибка вовсе)
Установил контекст подключения к файловой базе. Путь содержал кириллицу. Строка контекста была примерно такой: "/FD:Учеба\1С\Базы\МояСуперВажнаяБаза". Вызов процедуры ВыгрузитьбИнформационнуюБазу вернул следующую ошибку: 

```
ОШИБКА - Получен ненулевой код возврата 1. Выполнение скрипта остановлено!
{Модуль C:\Program Files\OneScript\lib\v8runner\src\v8runner.os / Ошибка в строке: 1400 / Информационная база не обнаружена!
}
```
Убрал кириллицу  из пути к базе - все заработало

П.С.
Только начал изучать 1Script - инструмент огонь. Огромное спасибо за него :)

**Comment by EvilBeaver** [comment]
Скорее всего проблема с кодировками в консоли, в которой запускаете. Оперативно позадавать вопросы можно в Телеграм https://t.me/oscript_library

> Только начал изучать 1Script - инструмент огонь. Огромное спасибо за него :)

Вам спасибо, что пользуетесь. Ждем в Телеге! 😄
