### ISSUE TITLE
Уточнить сообщение при ненулевом коде возврата.

### ISSUE THREAD

**Issue by aegoncharov1979** [oscript-library/v8runner#169]
В Функция ВыполнитьКоманду(Знач Параметры) Экспорт
...
```
	Если КодВозврата <> 0 И мИсключениеПриОшибкеВыполненияКоманды Тогда
		Лог.Ошибка("Получен ненулевой код возврата "+КодВозврата +". Выполнение скрипта остановлено!");
		ВызватьИсключение ВыводКоманды();
```

Пользователю выдается сообщение, что выполнение скрипта остановлено. Но это не так, скрипт, выполняющий команду не факт что останавливается, он просто обрабатывает это исключение в попытке и может пойти работать дальше. Сообщение вводит пользователя в заблуждение.
Предлагаю удалить код " +". Выполнение скрипта остановлено!"".

**Comment by EvilBeaver** [comment]
Поддержу. Это устаревшая много лет назад формулировка кода ошибки

**Comment by aegoncharov1979** [comment]
Сделал, надеюсь все правильно.

**Comment by EvilBeaver** [comment]
> Сделал, надеюсь все правильно.

Да, спасибо!
