### ISSUE TITLE
Валится ошибка при создании объекта УправлениеКонфигуратором()

### ISSUE THREAD

**Issue by solovyov-ilya** [oscript-library/v8runner#171]
Здравствуйте! Второй день бьюсь с проблемой, прошу помощи.

Код при попытке запуска валится с ошибкой:

> Unknown protocol. Using default
> {Модуль C:\OScript\lib\fluent\src\Классы\ПроцессорКоллекций.os / Ошибка в строке: 966 / Внешнее исключение (ScriptEngine.Compiler.CompilerException): {Модуль <string 0B4EDC33> / Ошибка в строке: 11,9 / Неизвестная операция}    
> 	Первый, Второй -> СтроковыеФункции.СравнитьВерсии(Первый.НомерВерсии,  Второй.НомерВерсии) < 0}

Версия: 1Script Execution Engine. Version 1.9.2.10
Библиотеки все свежие, с репозитория.

![image](https://github.com/user-attachments/assets/dc525b88-b97b-4653-af8d-4826ff1a1dba)

![image](https://github.com/user-attachments/assets/3f8fb5f2-6b0e-428c-bc8c-f6a2b68c274c)

Спасибо!

**Comment by solovyov-ilya** [comment]
А валится оно вот тут:
![image](https://github.com/user-attachments/assets/4219683d-3e59-4fe3-b61a-90dea82c1bd1)

**Comment by EvilBeaver** [comment]
@nixel2007 @sfaqer поможете? Что-то с флуентом, там вы эксперты

**Comment by nixel2007** [comment]
@EvilBeaver недавно было похожее. В v8find старая зависимость от флюента. Или он сам старый. Короче решится обновлением обеих библиотек - v8find и fluent

**Comment by solovyov-ilya** [comment]
@nixel2007
Да, обновил обе библиотеки - v8find и fluent, и все заработало. Спасибо!
