### ISSUE TITLE
Есть ли возможность динамического обновления расширений?

### ISSUE THREAD

**Issue by maselof** [oscript-library/v8runner#172]
Здравствуйте, искал в исходниках данный функционал, не нашел.
Хотел бы узнать, есть ли возможность добавить его, если его нет, или подскажите с какими флагами запускать.

Заранее спасибо за ответ!

**Comment by EvilBeaver** [comment]
Не подскажу, надо изучать справку по флагам запуска конфигуратора, а потом поискать эти флаги в коде v8runner.
