### ISSUE TITLE
Предложение сделать УстановитьКонтекстХранилища

### ISSUE THREAD

**Issue by Khorevaa** [oscript-library/v8runner#19]
Для того чтобы убрать дублирующий код вида 
```bsl 
        Параметры.Добавить("/ConfigurationRepositoryF """+ПапкаХранилища+"""");
	Параметры.Добавить("/ConfigurationRepositoryN """+ПользовательХранилища+"""");
	
	Если Не ПустаяСтрока(ПарольХранилища) Тогда
		Параметры.Добавить("/ConfigurationRepositoryP """+ПарольХранилища+"""");
	КонецЕсли;	
```

Предлагаю сделать аналогичные подключению к БД  команды УстановитьКонтекст, ПолучитьКонтекст, ИспользоватьКонтекст только для хранилища

**Comment by nixel2007** [comment]
Без поломки апи получится сделать?

**Comment by EvilBeaver** [comment]
А я предлагаю пойти дальше. Сделать класс УправлениеХранилищемКонфигурации. А общий код между старым "Управлением" и новым - вынести в общий модуль.

**Comment by nixel2007** [comment]
@EvilBeaver дай админа в этом репо. Сорри за флуд.

**Comment by EvilBeaver** [comment]
@nixel2007 done

**Comment by nixel2007** [comment]
@EvilBeaver и апрув на авторизацию приложений =( запросил доступ. спасибо!

**Comment by EvilBeaver** [comment]
@nixel2007 там админский доступ к репе. Не понял, что еще нужно. И раз уж этот оффтоп разросся - перейдем в скайп?

**Comment by Khorevaa** [comment]
@EvilBeaver Идея понятна. Но вот стоит?

**Comment by artbear** [comment]
>А я предлагаю пойти дальше. Сделать класс УправлениеХранилищемКонфигурации. А общий код между старым "Управлением" и новым - вынести в общий модуль.

Поддержу @EvilBeaver 
Также об этом задумался.
Новая сущность четко соответствует новым решаемым задачам.
Нафига тащить в v8runner весь код по работе с хранилищем.
