### ISSUE TITLE
Не удаляются файлы выхлопа 1С:Предприятия

### ISSUE THREAD

**Issue by EvilBeaver** [oscript-library/v8runner#2]
В рабочем каталоге v8runner накапливаются файлы с выводом 1С:Предприятия.

Поведение вызвано: https://github.com/oscript-library/v8runner/commit/281d0eac4ee46611b603fdb8b432ead4a6ae0609

Нужно найти, почему не чистит, ибо по коду - должно

**Comment by artbear** [comment]
А где ты по коду увидел, что должно чиститься?
Используется метод `ПолучитьИмяВременногоФайла`, который не убирает за собой.
ИМХО нужно
+ или юзать ВременныеФайлы внутри библиотеки вместо  `ПолучитьИмяВременногоФайла`
+ или клиент библиотеки должен сам отслеживать удаление этого файла

**Comment by EvilBeaver** [comment]
там где-то было при очередном запуске удаление

**Comment by artbear** [comment]
Где? 
мы обсуждали подобное решение, как делает 1С, но ИМХО не стали делать.
У нас не 1С, у нас скриптинг!

**Comment by EvilBeaver** [comment]
@artbear не торопись, я вообще о другом.

**Comment by Stepa86** [comment]
Предлагаю в методе ПрочитатьФайлИнформации() в файле v8runner.os удалять временный файл после чтения.

**Comment by EvilBeaver** [comment]
@Stepa86 а хорошая мысль. Плюсадин

**Comment by artbear** [comment]
>Предлагаю в методе ПрочитатьФайлИнформации() в файле v8runner.os удалять временный файл после чтения.

ИМХО предложение с удалением правильное, а вот реализация не очень.
1 Метод чтения не должен удалять файлы :)
2 нужно явно указать, что файл удаляется
3 а вдруг еще раз захотим читать файл, а его уже нет

Предлагаю выполнить рефакторинг:
у нас метод `ПрочитатьФайлИнформации` вызывается всегда при вызове `УстановитьВывод`
Сделать:
+ либо вызывать метод `УдалитьФайлИнформации` после вызова `УстановитьВывод(ПрочитатьФайлИнформации)`
  + куча дублирующего кода из 2-3 строка
+ либо сделать спец.метод, который устанавливает вывод из файла информации и удаляет файл информации. 
  + Правда, имя этого метода что-то у меня не придумывается.

А вообще в будущем, я хотел часть по вызову Конфигуратора и отработке вывода от него отдать в 1commands и решить в нем эти вопросы :)
Можно и сейчас решить, а потом перенесем.

**Comment by Stepa86** [comment]
@artbear Есть 2 варианта работы. 1) Файл никто специально не устанавливает, он используется для получения информации о выводе только и имеет временное имя. Инкапсулировать его в ПрочитатьФайлИнформации(), где отсутствие файла будет считаться, что там пусто. Вообще работает получение вывода через файл или еще как то - это тонкости реализации, которые внаружу можно не высвечивать.
2) Файл установлен явно (причем нужно еще учитывать флаг NoTruncate по хорошему то), вот тогда его не нужно удалять и перед выполнением команды

И я не очень вижу, чтобы второй вариант сейчас вообще поддерживался, т.к. файл все равно удаляется в ВыполнитьКоманду

**Comment by Stepa86** [comment]
Файл информации имеет смысл только внутри метода ЗапуститьИПодождать. 

Можно добавить флаг мИспользуетсяВнешнийФайлСообщений, который будет взводиться в УстановитьИмяФайлаСообщенийПлатформы( и еще один флаг для NoTruncate, например мОчищатьФайл.

Установку файла и добавление его к строке запуска выполнять внутри ЗапуститьИПодождать, а после ЗапуститьПриложение( сразу читать файл в мВыводКоманды (если стоит флаг мОчищатьФайл, то мВыводКоманды = мВыводКоманды + новыйТекст) и удалять, если мИспользуетсяВнешнийФайлСообщений = Ложь.

**Comment by Stepa86** [comment]
@artbear 
> А вообще в будущем, я хотел часть по вызову Конфигуратора и отработке вывода от него отдать в 1commands и решить в нем эти вопросы :)

А разве строка команды /Out <имя файла> [-NoTruncate]] не чисто 1Сная? Не делать же в 1commands  определение, что если это 1Ска, то играемся с файлом вывода, а если нет, то не очень. Ну и переопределение имени файла должно решаться на уровне раннера.

**Comment by artbear** [comment]
@Stepa86 Ишуз "Получение вывода команды, у которой есть отдельный лог-файл" https://github.com/artbear/1commands/issues/4

Предполагаю заведение спец.метода для указания пути подобного лог-файла и исключения привязки к конкретным параметрам.

**Comment by artbear** [comment]
@Stepa86 Про внешний файл очень хорошее замечание, обязательно нужно учесть.
Спасибо.

**Comment by EvilBeaver** [comment]
@artbear давайте не примешивать сюда 1СКоммандс, а решим конкретную проблему - накопление файлов после работы v8runner. Они почему-то не удаляются, хотя, как правильно заметил @Stepa86 - удаление там есть внутри ВыполнитьКоманду. Но почему-то не работает. Вот это и надо решить. А лучшее решение - грохать файл сразу же, как только сделали УстановитьВывод и считали этот файл в переменную. Больше он не нужен.

**Comment by Stepa86** [comment]
@EvilBeaver Удаление есть только до запуска приложения, так сказать удаление старого файла. Потом выполняется запуск приложения, оно создает файл и его уже никто не удаляет

**Comment by EvilBeaver** [comment]
Ну тогда надо его грохать сразу в УстановитьВывод после запуска приложения.

**Comment by artbear** [comment]
Давно выполнено
