### ISSUE TITLE
Зачем принудительная установка "аутентификации ОС"

### ISSUE THREAD

**Issue by CT144** [oscript-library/v8runner#24]
При запуске конфигуратора/предприятия в строку запуска устанавливается параметр /WA+, а параметр пароль(/P) игнорируется. Зачем?

**Comment by nixel2007** [comment]
Пароль не игнорируется, он просто не выводится в лог дабы не утечь

**Comment by CT144** [comment]
Согласен, недоанализировал. Но "/WA+" ставиться, что в соответствии с "желтыми" книжками означает: "установка обязательного применения аутентификации операционной системы при старте «1С:Предприятие»".

**Comment by nixel2007** [comment]
Я правильно понимаю, что такая комбинация флагов приводит к аутентификации средствами ОС, не взирая на логин/пароль, переданный в параметрах?

**Comment by CT144** [comment]
Да.

**Comment by CT144** [comment]
Практика показала, что при одновременном задании логин/пароль и /WA+ "побеждает" пара логин/пароль. Был не прав.

**Comment by nixel2007** [comment]
Думаю, можно оставить эту задачу открытой, чтобы поправить установку WA+ -  ставить его только в случае, когда не переданы логин и пароль
