### ISSUE TITLE
Поиск версии платформы и сортировка для максимальной неверно работает с 8.3.10

### ISSUE THREAD

**Issue by pumbaEO** [oscript-library/v8runner#25]
В случаи установки 8.3.10 все равно выбирает 8.3.9 для определения максимальной версии.

**Comment by nixel2007** [comment]
вроде там должно работать сравнение по числам. неужели по строке сравнивает?

**Comment by pumbaEO** [comment]
ну так 1 меньше же чем 9 :)

**Comment by nixel2007** [comment]
я к тому, что там вроде было разбитие на блоки между точками.

**Comment by EvilBeaver** [comment]
нам кажется, что было. Оно было в opm точно. А в runner - не факт.

**Comment by Stepa86** [comment]
В методе ПолучитьПутьКВерсииПлатформы( такой код
```bsl
МаксВерсия = МассивКаталоговВерсий[0].Имя;
			НужныйФайлПлатформы = Новый Файл(ОбъединитьПути(МассивКаталоговВерсий[0].ПолноеИмя, "bin", "1cv8.exe"));

			Для Сч = 1 По МассивКаталоговВерсий.ВГраница() Цикл
				ТекущаяВерсия = МассивКаталоговВерсий[Сч].Имя;
				Если МаксВерсия < ТекущаяВерсия Тогда
					ПутьБин = ОбъединитьПути(МассивКаталоговВерсий[Сч].ПолноеИмя, "bin");
					ПроверяемыйФайл = Новый Файл(ОбъединитьПути(ПутьБин, "1cv8.exe"));
					Если НЕ ПроверяемыйФайл.Существует() Тогда
						Продолжить;
					КонецЕсли;

					МаксВерсия = ТекущаяВерсия;
					НужныйФайлПлатформы = ПроверяемыйФайл;
				КонецЕсли;
			КонецЦикла;
```

То есть сравнивается 2 строки. Для сравнений двух версий можно взять из типовой метод

```bsl
// Сравнить две строки версий.
//
// Параметры:
//  СтрокаВерсии1  - Строка - номер версии в формате РР.{П|ПП}.ЗЗ.СС.
//  СтрокаВерсии2  - Строка - второй сравниваемый номер версии.
//
// Возвращаемое значение:
//   Число   - больше 0, если СтрокаВерсии1 > СтрокаВерсии2; 0, если версии равны.
//
Функция СравнитьВерсии(Знач СтрокаВерсии1, Знач СтрокаВерсии2) Экспорт
	
	Строка1 = ?(ПустаяСтрока(СтрокаВерсии1), "0.0.0.0", СтрокаВерсии1);
	Строка2 = ?(ПустаяСтрока(СтрокаВерсии2), "0.0.0.0", СтрокаВерсии2);
	Версия1 = СтрРазделить(Строка1, ".");
	Если Версия1.Количество() <> 4 Тогда
		ВызватьИсключение СтроковыеФункцииКлиентСервер.ПодставитьПараметрыВСтроку(
			НСтр("ru = 'Неправильный формат параметра СтрокаВерсии1: %1'"), СтрокаВерсии1);
	КонецЕсли;
	Версия2 = СтрРазделить(Строка2, ".");
	Если Версия2.Количество() <> 4 Тогда
		ВызватьИсключение СтроковыеФункцииКлиентСервер.ПодставитьПараметрыВСтроку(
	    	НСтр("ru = 'Неправильный формат параметра СтрокаВерсии2: %1'"), СтрокаВерсии2);
	КонецЕсли;
	
	Результат = 0;
	Для Разряд = 0 По 3 Цикл
		Результат = Число(Версия1[Разряд]) - Число(Версия2[Разряд]);
		Если Результат <> 0 Тогда
			Возврат Результат;
		КонецЕсли;
	КонецЦикла;
	Возврат Результат;
	
КонецФункции
```
Но это логичнее вставить в библиотеку строк и уже ее подключить к v8runner

**Comment by EvilBeaver** [comment]
@Stepa86 я вообще хочу выпилить библиотеку строк в текущем виде, ибо это код БСП, а его лицензионная чистота не до конца ясна. Поэтому, я бы порекомендовал взять метод сравнения версий из OPM. Или скопипастить предложенный тобой метод напрямую в v8runner, вместо перенесения его в strings.

**Comment by Stepa86** [comment]
@EvilBeaver А мой код так же из БСП. Насколько я понимаю лицензию - достаточно указать в заголовке файла, что этот код взят из БСП.
А еще в типовых этот код лежит в модуле ОбщегоНазначения, а не в СтроковыеФункции.

**Comment by artbear** [comment]
@EvilBeaver @nixel2007 Предлагаю код сравнения версий выпилить из opm и 
+ либо добавить в СтроковыеФункции
+ либо сделать новую библиотеку Версии

**Comment by nixel2007** [comment]
ишуз на библиотеку semver уже есть.

**Comment by EvilBeaver** [comment]
@Stepa86 а можешь ткнуть в место лицензии, в котором написано про заголовок и все такое?

**Comment by Stepa86** [comment]
https://1c.ru/news/info.jsp?id=11853 пункт Состав, порядок распространения и использования 
"1С:Библиотеки стандартных подсистем 8.2"

"Фирма "1С" разрешает использование БСП зарегистрированным пользователям системы "1С:Предприятие 8" версии ПРОФ, имеющим действующую подписку на ИТС, для разработки прикладных решений, предназначенных как для собственной автоматизации, так и для тиражирования, без дополнительной оплаты.

При тиражировании прикладных решений, которые используют БСП, должны соблюдаться авторские права фирмы "1С" на систему "1С:Предприятие 8", в частности, использование таких конфигураций допускается только при наличии у пользователя правомерно приобретенной основной поставки "1С:Предприятия 8". Информация о том, что тиражное решение разработано с использованием "1С:Библиотека стандартных подсистем 8.2" должно быть отражено:

на основной веб-странице, описывающей данное прикладное решение;
в документации по прикладному решению во введении или на страницах до введения;
в пресс-релизах и информационных сообщениях, сопровождающих выпуск нового решения.
В то же время, использование прикладного решения, разработанного с применением БСП, возможно без подписки на ИТС при одновременном выполнении следующих условий:

правообладатель прикладного решения не требует обязательной подписки на ИТС,
пользователь самостоятельно не осуществляет доработку прикладного решения с применением БСП."

Про использование фрагментов кода в опенсорсе конечно не очень много написано.

**Comment by Stepa86** [comment]
@EvilBeaver "Официальная позиция 1С - мы все придумали, сейчас на согласовании" https://partners.v8.1c.ru/forum/topic/1487714  но пока не согласуют - ничего не скажут

**Comment by EvilBeaver** [comment]
> "Фирма "1С" разрешает использование БСП зарегистрированным пользователям системы "1С:Предприятие 8" версии ПРОФ, имеющим действующую подписку на ИТС, для разработки прикладных решений, предназначенных как для собственной автоматизации, так и для тиражирования, без дополнительной оплаты.

Вот здесь - основная загвоздка: У кого должна быть подписка ИТС в случае сообщества разработчиков?

**Comment by artbear** [comment]
Давно выполнено
