### ISSUE TITLE
На работает тестирование проекта

### ISSUE THREAD

**Issue by Khorevaa** [oscript-library/v8runner#27]
Все установлена последняя версия1testrunner 1.4.2

Запуск теста выдает
{Модуль C:\Program Files (x86)\OneScript\lib\1testrunner\main.os / Ошибка в строке: 0 / Ошибка загрузки библиотеки C:\Program Files (x86)\OneScript\lib\1testrunner. Обнаружены циклические зависимости}

**Comment by nixel2007** [comment]
Попробуй удалить тестраннер и поставить заново

**Comment by artbear** [comment]
Подтверждаю проблему :(

**Comment by artbear** [comment]
Источником ошибки является 1testrunner https://github.com/artbear/1testrunner/issues/15
Ошибка исправлена в релизе 1.4.3 

Ждем, пока @nixel2007 опубликует релиз.

**Comment by nixel2007** [comment]
Опубликовано, обновляйтесь.

2017-02-02 13:16 GMT+03:00 Artur Ayukhanov <notifications@github.com>:
