### ISSUE TITLE
Добавить кеширование поиска платформы

### ISSUE THREAD

**Issue by artbear** [oscript-library/v8runner#40]
>@pumbaEO:
в v8runner тоже на каждый пчих делает поиск платформы, хотя можно и закешировать.

кешировать нужно, если не меняется переданная версия платформы

**Comment by EvilBeaver** [comment]
Пусть будет, чо. Может кто придет и сделает доброе дело, пришлет пулреквест...

**Comment by pumbaEO** [comment]
При частых запусках v8runner имхо нет необходимости делать поиск новой платформы, т.е. я бы сделал файл кэша с платформами и там его проверял, старше чем 5 минут - можно обновить список установленных.

**Comment by EvilBeaver** [comment]
Можно проще. Не нашел в кеше, поискал. Нашел - в кэш.

**Comment by khorevaa** [comment]
Сделан в 1.3.0
