### ISSUE TITLE
Документировать новые методы продукта

### ISSUE THREAD

**Issue by artbear** [oscript-library/v8runner#43]
А то народ ругается в https://infostart.ru/public/699642/ :)
>Список доступных методов в README безбожно устарел, для осознания всей мощи инструмента стоит заглянуть в исходники.

**Comment by lo0p3r** [comment]
Обновил описание методов: 9c7f1d2d48f48a7136f846e97190ed2721e4c36c

**Comment by EvilBeaver** [comment]
@artbear посмотришь пулреквест?

**Comment by artbear** [comment]
Добавлено описание в #154 , закрываю
