### ISSUE TITLE
Предложение - Добавить параметр с произвольными ключами запуска в функцию ОбновитьКонфигурациюБазыДанных()

### ISSUE THREAD

**Issue by ripreal** [oscript-library/v8runner#44]
В продакшене у меня есть скрипт, который обновляет базу данных с ключом /UCПакетноеОбновлениеКонфигурацииИБ.  

Сейчас неудобно пользоваться функцией ОбновитьКонфигурациюБазыДанных() в модуле v8Runner, т.к. туда нельзя передать дополнительные ключи запуска. 

Предлагаю следующие изменения по аналогии с  ЗапуститьВРежимеПредприятия():

``` bsl
Процедура ОбновитьКонфигурациюБазыДанных(
	ПредупрежденияКакОшибки = Ложь, НаСервере = Истина, 
	ДинамическоеОбновление = Ложь,
	ИмяРасширения = "",
	Знач ДополнительныеКлючи = Неопределено ) Экспорт // ДОБАВЛЕН ПАРАМЕТР ДополнительныеКлючи 

	ПараметрыСвязиСБазой = СтандартныеПараметрыЗапускаКонфигуратора();

	ПараметрыСвязиСБазой.Добавить("/UpdateDBCfg");
	Если Не ДинамическоеОбновление Тогда
		ПараметрыСвязиСБазой.Добавить("-Dynamic-");
	КонецЕсли;
	
	Если ПредупрежденияКакОшибки Тогда
		ПараметрыСвязиСБазой.Добавить("-WarningsAsErrors");
	КонецЕсли;
	Если НаСервере Тогда
		ПараметрыСвязиСБазой.Добавить("-Server");
	КонецЕсли;
	Если ИмяРасширения <> "" Тогда
		ПараметрыСвязиСБазой.Добавить("-Extension " + ИмяРасширения);
	КонецЕсли;
      
       // ОБРАБОТКА ДОПОЛНИТЕЛЬНОГО ПАРАМЕТРА
	Если ДополнительныеКлючи <> Неопределено Тогда
		ПараметрыСвязиСБазой.Добавить(ДополнительныеКлючи);
	КонецЕсли;
        // ОБРАБОТКА ДОПОЛНИТЕЛЬНОГО ПАРАМЕТРА

	ВыполнитьКоманду(ПараметрыСвязиСБазой);

КонецПроцедуры
```

**Comment by EvilBeaver** [comment]
А какие там возможны дополнительные ключи?

**Comment by ripreal** [comment]
"/UCПакетноеОбновлениеКонфигурацииИБ. ". Я его использую, чтобы зайти в конфигуратор с установленной блокировкой сеансов и обновить сразу базу.

**Comment by EvilBeaver** [comment]
Там вроде бы есть проброс ключа UC. Деплойка как-то же это делает... Но не могу вспомнить как.

**Comment by ripreal** [comment]
Там сделано через Конфигуратор.ВыполнитьКоманду(ПараметрыЗапуска). А она слишком "низкоуровневая", если хочется использовать типовую ОбновитьКонфигурациюБазыДанных()

**Comment by EvilBeaver** [comment]
Ясно. Конечно надо добавить ключ UC. Только наверное, надо добавить именно его, через явный параметр "КлючРазрешенияЗапуска", если других возможных "доп. параметров" нет.

**Comment by ripreal** [comment]
НЕ получится, т.к. в процедуре СтандартныеПараметрыЗапускаКонфигуратора() неправильно отрабатывает параметр "КлючРазрешенияЗАпуска" ИЗ-ЗА ОбернутьВКавычки.  Зачем это делается? Ведь в итоге получается "/UC"ПакетноеОбновлениеКонфигурацииИБ"", а нужно "/UCПакетноеОбновлениеКонфигурацииИБ."
``` bsl
ПараметрыЗапуска.Добавить("/UC" + ОбернутьВКавычки(мКонтекстКоманды.КлючРазрешенияЗапуска));
``` bsl

Все-таки хотлеось бы использовать изначально предложенный вариант в первом посте, потому что могут потребоваться дополнительные кастомные ключи запуска, например чтобы запускать сразу автотесты или что-то вроде того,

**Comment by EvilBeaver** [comment]
> Ведь в итоге получается "/UC"ПакетноеОбновлениеКонфигурацииИБ"", а нужно "/UCПакетноеОбновлениеКонфигурацииИБ."

Тогда именно это и надо исправить.

> могут потребоваться дополнительные кастомные ключи запуска, например чтобы запускать сразу автотесты или что-то вроде того

Автотесты в процедуре обновления конфигурации ИБ - это нонсенс. Это часть "конфигураторная", в ней тесты не запускаются. Именно поэтому, я спрашивал про конкретные случаи и конкретные параметры. Подход "универсальных" параметров "на всякий случай" - это зло.

**Comment by ripreal** [comment]
ОК, я тогда исправлю эту строку
``` bsl
ПараметрыЗапуска.Добавить("/UC" + ОбернутьВКавычки(мКонтекстКоманды.КлючРазрешенияЗапуска));

**Comment by EvilBeaver** [comment]
Кстати, а почему это исправление нужно? Разве сейчас сделано неверно?

**Comment by ripreal** [comment]
Выхожит /UC"ПакетноеОбновлениеКонфигурацииИБ"", а нужно "/UCПакетноеОбновлениеКонфигурацииИБ."

**Comment by EvilBeaver** [comment]
@ripreal почему "нужно"? В чем разница с точки зрения поведения системы? Я просто всю жизнь запускал именно так, @artbear не даст соврать. Может, я что-то упускаю?

**Comment by ripreal** [comment]
Разобрался, действительно без разницы где кавычки стоят. Закрываю тему.
