### ISSUE TITLE
Проблема выполнения команды создания Серверной ИБ

### ISSUE THREAD

**Issue by arkuznetsov** [oscript-library/v8runner#52]
Добавил в библиотеку процедуру создания серверной ИБ https://github.com/arkuznetsov/v8runner/blob/38bb6fe2ee9d3d2b710f68b4b2f7eef13e96b2f0/src/v8runner.os#L860 возникла проблема с выполнением команды 1С:
Формируется строка запуска (в 1commands): 
```
"C:\Program Files\1cv8\8.3.10.2561\bin\1cv8.exe" CREATEINFOBASE` Srvr=Sport1;Ref=TST_CPDB;DBMS=MSSQLServer;DBSrvr=Sport1;DBUID=_1CSrvUsr1;DBPwd=q2w3e4r5;DB=TST_CPDB;SQLYOffs=2000;CrSQLDB=Y;SchJobDn=Y /Out `"d:\Repo\cpdb\55o2xmid.xfq.txt"
```
и передается на ветку с использованием командного процессора, что в итоге дает:
```
cmd /c "C:\Program Files\1cv8\8.3.10.2561\bin\1cv8.exe" CREATEINFOBASE Srvr=Sport1;Ref=TST_CPDB;DBMS=MSSQLServer;DBSrvr=Sport1;DBUID=_1CSrvUsr1;DBPwd=q2w3e4r5;DB=TST_CPDB;SQLYOffs=2000;CrSQLDB=Y;SchJobDn=Y /Out "d:\Repo\cpdb\pojw0h4d.q0v.txt"
```
и вызывает ошибку:
```
ОШИБКА - "C:\Program" ?? ????? ???????? ??? ?????????????, ??????? ?????? ??? ?????? ????.
```
если дополнительно обернуть в кавычки команду передаваемую в cmd:
```
cmd /c ""C:\Program Files\1cv8\8.3.10.2561\bin\1cv8.exe" CREATEINFOBASE Srvr=Sport1;Ref=TST_CPDB;DBMS=MSSQLServer;DBSrvr=Sport1;DBUID=_1CSrvUsr1;DBPwd=q2w3e4r5;DB=TST_CPDB;SQLYOffs=2000;CrSQLDB=Y;SchJobDn=Y /Out "d:\Repo\cpdb\pojw0h4d.q0v.txt""
```
, то все норм.

**Comment by artbear** [comment]
А причем здесь 1коммандс? он же в коде не вызывается вроде бы

**Comment by arkuznetsov** [comment]
Тут: https://github.com/arkuznetsov/v8runner/blob/38bb6fe2ee9d3d2b710f68b4b2f7eef13e96b2f0/src/v8runner.os#L1505

**Comment by Khorevaa** [comment]
Станное поведение...
Оберни в ковычки параметр "Srvr=....."

**Comment by arkuznetsov** [comment]
Обернул, не помогло. :-(

**Comment by Khorevaa** [comment]
Да надо дополнительно для windows оборачивать строку "приложения" в двойные кавычки.... На linux такой проблемы неть...

**Comment by arkuznetsov** [comment]
Для Linux там, кстати, в одинарные оборачивается.
А с какой целью v8runner запускает команды через cmd?

**Comment by Khorevaa** [comment]
@arkuznetsov  Так это не v8runner а 1commands работает через cmd и sh вроде как....Вообще странно а другие команды проходят..? Тоже не должны...

**Comment by nixel2007** [comment]
Я вот тоже не совсем понимаю, зачем принудительное оборачивание в cmd...

**Comment by arkuznetsov** [comment]
@Khorevaa, @nixel2007: Там в 1command вроде как 2 ветки есть от переменной ИспользуемКомандныйПроцессор, которая по умолчанию Истина, И в v8runner в процедуре ЗапуститьИПодождать установки этой переменной не происходит. Т.е. нужно решить где править.

**Comment by artbear** [comment]
Весело тут у вас :)

>nixel2007 commented 2 hours ago
Я вот тоже не совсем понимаю, зачем принудительное оборачивание в cmd...

Смотрим https://github.com/artbear/1commands/issues/13

Автор тот же, время назад :)

>nixel2007 commented on 11 Jan
Нененененене. Инкапсуляцию хочу. Вот прям совсем хочу.
У меня есть 1bdd.bat на винде и 1bdd (который sh) на линуксе. CMD по умолчанию умеет искать файлы с дополнением имени по зарегистрированному расширению (есть отдельная переменная среды).

>Хочу навсегда забыть об этом аде с cmd /c
Если скриптописатель ~упоротый~ упёртый и хочет творить эту магию с cmd /c /// sh -c (и ему нужны какие-то доп флаги или явно нужно указать интерпретатор) - то флаг ему в руки. А как обыватель я не хочу про это думать. На винде есть стандартный командный процессор. На линуксе он дефакто тоже есть - sh. Пусть вся эта магия будет скрыта.

>P.S. Больше магии в одном сообщений.

Точно магия :)

**Comment by artbear** [comment]
@arkuznetsov Да, нужно использовать именно `Команда.УстановитьИсполнениеЧерезКомандыСистемы(Ложь);`

потому что cmd для запуска 1С не нужен совсем

**Comment by artbear** [comment]
ОФФ Я призвался :)

**Comment by arkuznetsov** [comment]
@artbear: Т.е. я добавляю в v8runner в ЗапуститьИПодождать:
```
Команда.УстановитьИсполнениеЧерезКомандыСистемы(Ложь);
```
и делаю PR? :-)

**Comment by artbear** [comment]
@arkuznetsov Да, конечно.
