### ISSUE TITLE
После вызова ВыполнитьКоманду() отключается логирование в вызывающем скрипте

### ISSUE THREAD

**Issue by arkuznetsov** [oscript-library/v8runner#56]
Возникла проблема с логами. Симптомы:
После вызова v8runner.ВыполнитьКоманду() в вызывающем модуле перестает писаться лог (Лог.Информация(...) не выводит ничего).
Что удалось раскопать:
В v8runner, в процедуре ЗапуститьИПодождать есть строка:
```
Команда.ДобавитьЛогВыводаКоманды("oscript.lib.v8runner");
```
Если ее убрать или в параметре указать имя несуществующего в контексте лога, то проблема уходит.

**Comment by nixel2007** [comment]
@artbear

**Comment by artbear** [comment]
Исправлено - выпущены релиз `1commands 1.3.1` и релиз `v8runner 1.0.0`
