### ISSUE TITLE
Проблемы при неоднократном использовании объекта конфигуртора

### ISSUE THREAD

**Issue by ArchLord42RU** [oscript-library/v8runner#64]
При пакетной работе с конфигуратором через объект
Конфигуратор = Новый УправлениеКонфигуратором();
Конфигуратор.УстановитьКонтекст(блаблабла);

Не всегда (но часто) вываливается ошибка

15.02.2018 17:13:42: КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\v8runner\src\v8config-file.os / Ошибка в строке: 15 / Внешнее исключение (System.IO.IOException): Процесс не может получить доступ к файлу "C:\ProgramData\1C\1CEStart\1CEStart.cfg", так как этот файл используется другим процессом.}
        ЧтениеТекста = Новый ЧтениеТекста(Путь);

валится как же ясно в файле v8config-file.os на методе "Открыть"

Процедура Открыть(Знач Путь) Экспорт

	ЧтениеТекста = Новый ЧтениеТекста(Путь);
	
	мСодержимое = Новый Соответствие;
	
	СтрокаФайла = "";
	Пока Не СтрокаФайла = Неопределено Цикл
		
		СтрокаФайла = ЧтениеТекста.ПрочитатьСтроку();
		Если СтрокаФайла = Неопределено Тогда
			Прервать;
		КонецЕсли;
		
		Данные = КлючИЗначение(СтрокаФайла);
		Если Данные = Неопределено Тогда
			Продолжить;
		КонецЕсли;
		
		ДобавитьПараметр(Данные);
		
	КонецЦикла;

КонецПроцедуры

Собственно проблема в том, что объект чтение текста не закрывается.

**Comment by EvilBeaver** [comment]
Нужно исправить на немонопольное открытие файла конструктором ЧтенияТекста

**Comment by ArchLord42RU** [comment]
эх, ничему жизнь не учит :)
@artbear уже фиксил это, в конце декабря, сделал opm update, там как раз исправление открытия файла с немонопольным доступом, но закрытия объект так и не добавлено, собственно остался 1 вопрос, нужен ли ПР с фиксом этим?

**Comment by EvilBeaver** [comment]
Нужен
