### ISSUE TITLE
Сделать отдельные методы для загрузки/выгрузки расширений

### ISSUE THREAD

**Issue by artbear** [oscript-library/v8runner#70]
в продолжение https://github.com/oscript-library/v8runner/pull/69#issuecomment-370810647

- [x] добавить новый метод `ЗагрузитьРасширениеИзФайла`
- [x] добавить новый метод `ВыгрузитьРасширениеВФайл`
- [x] убрать параметр ИмяРасширения из метода `ЗагрузитьКонфигурациюИзФайла`
- [x] убрать параметр ИмяРасширения из метода `ВыгрузитьКонфигурациюВФайл`

**Comment by artbear** [comment]
@Berckk сможешь сделать в продолжение своего же PR ?

**Comment by Berckk** [comment]
Хорошо. Займусь.

**Comment by artbear** [comment]
Отлично. ждем.
и тогда можно будет в vanessa-runner упростить код и отказаться от использования ком.строки Конфигуратора при работе с расширениями.
