### ISSUE TITLE
Обновление пакета на актуальную версию ветки master

### ISSUE THREAD

**Issue by Dumsik** [oscript-library/v8runner#77]
Товарищи, можно обновить пакет v8runner в хабе пакетов, на актуальную версию  ветки master. 
Есть неприятные баги которые поправлены и уже включены в ветку master, а в хабе пакет старый.
Пример исправленного бага https://github.com/oscript-library/v8runner/commit/f12377ea89486720161648e3181773c8c864f421

**Comment by Dumsik** [comment]
> Сделаю. Если не сделаю, пни меня здесь же через пару дней.

Пинаю:)

**Comment by Berckk** [comment]
А можно комиты из ветки develop тоже уже увидеть в пакете в хабе?

**Comment by EvilBeaver** [comment]
@Dumsik вечером постараюсь сделать

**Comment by EvilBeaver** [comment]
Запушил новую версию.
