### ISSUE TITLE
Флаг использование 2 версии механизма реструкторизации 8.3.14

### ISSUE THREAD

**Issue by khorevaa** [oscript-library/v8runner#83]
● -v1|-v2 ‑ определяет используемый механизм реструктуризации. Если не указана версия механизма реструктуризации (-v1 или -v2), то будет использоваться механизм реструктуризации той версии, которая указана в файле conf.cfg (на стороне клиентского приложения). В противном случае будет использована указанная версия механизма. Если указан оптимизированный механизм реструктуризации, но использование этого механизма конфликтует с другими параметрами ‑ будет использован обычный механизм реструктуризации.

**Comment by artbear** [comment]
выполнено в #106
