### ISSUE TITLE
При удалении временной Базы, удалять ее так же из списка.

### ISSUE THREAD

**Issue by ViktorErmakov** [oscript-library/v8runner#90]
Добавить в метод "УдалитьВременнуюБазу()" возможность, что бы база так же удалялась из прописанных баз.

**Comment by EvilBeaver** [comment]
А как она туда попадает? v8runner не пишет ничего в файл баз.

**Comment by ViktorErmakov** [comment]
Вот этот метод, создает базу, а так же добавляет ее в список баз
![изображение](https://user-images.githubusercontent.com/39617680/54707337-e2bd4600-4b51-11e9-8a4c-2f3a736aa0b4.png)
![изображение](https://user-images.githubusercontent.com/39617680/54707365-f668ac80-4b51-11e9-84dc-4d45709a4fb3.png)

**Comment by EvilBeaver** [comment]
Это 2 разных метода. УдалитьВременнуюБазу - это для работы с временным контекстом, для разовых операций. Парныйк нему метод - СоздатьВременнуюБазу. А приведенный Вами пример - полноценное создание базы.

**Comment by ViktorErmakov** [comment]
Прошу прощения, ишуз тогда закрыть можно будет. 
Главное метод УдалитьВременнуюБазу удалил мою полноценно созданную, потому как я использовал Конфигуратор.ПутьКВременнойБазе() при создании.
Может тогда нужно написать метод по удалению полноценно созданной базы?)
