### ISSUE TITLE
Как подключиться к серверной информационной базе?

### ISSUE THREAD

**Issue by testforgity** [oscript-library/v8runner#95]
Как подключиться к серверной информационной базе? У меня есть Srvr="ЦИФРЫ"; Ref="БУКВЫ"? Буду оочень благодарен.

**Comment by nixel2007** [comment]
Здравствуйте. В README есть пример подключения к серверной базе через /IBConnectionString

https://github.com/oscript-library/v8runner#%D0%BF%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B

так же можно преобразовать подключение для `/S`-строки

**Comment by testforgity** [comment]
я скопировал код: У меня разве 1с не должен открыться уже готовый? У меня выскакивает выбор информационной базы
#Использовать v8runner
Конфигуратор = Новый УправлениеКонфигуратором();

Конфигуратор.УстановитьКонтекст("/IBConnectionString""Srvr=ЦИФРЫ; Ref='БУКВЫ'""","Администратор", "ПАРОЛЬ");
ПараметрыЗапуска = УправлениеКонфигуратором.ПолучитьПараметрыЗапуска();
ПараметрыЗапуска.Добавить("/LoadCfg""C:/Users/practic/Desktop/cfg/1Cv8.cf"); 
Попытка
    УправлениеКонфигуратором.ВыполнитьКоманду(ПараметрыЗапуска);
	Сообщить(УправлениеКонфигуратором.ВыводКоманды())
	Сообщить(AAAAAAAAAAAAA)
Исключение
    // вывод log-файла с сообщениями от платформы.
    Сообщить(УправлениеКонфигуратором.ВыводКоманды());
КонецПопытки

**Comment by testforgity** [comment]
с 1с вообще не работал, поэтому все идет тяжко(перешел с таких низов как: python, c++)

**Comment by nixel2007** [comment]
вы контекст устанавливаете у инстанса "Конфигуратор", а параметры запуска и выполнение команды делаете у инстанса "УправлениеКонфигуратором". Оставьте только один инстанс

**Comment by testforgity** [comment]
Правильно?

#Использовать v8runner
Конфигуратор = Новый УправлениеКонфигуратором();

Конфигуратор.УстановитьКонтекст("/IBConnectionString" "Srvr=10.1.2.91; Ref='tagras_do'""","Администратор", "521226");
ПараметрыЗапуска = Конфигуратор.ПолучитьПараметрыЗапуска();
ПараметрыЗапуска.Добавить("/LoadCfg", "C:/Users/practic/Desktop/cfg/1Cv8.cf"); 
Конфигуратор.ВыполнитьКоманду(ПараметрыЗапуска);

**Comment by nixel2007** [comment]
да, например, так.

**Comment by testforgity** [comment]
:( не работает, как и до этого выводит список информационных баз

**Comment by testforgity** [comment]
попробовал так, но тоже открывает лишь список информационных баз, хотя (как я понимаю) должно открывать конфигурацию уже в заданной базе или я ошибаюсь?
#Использовать v8runner
УправлениеКонфигуратором = Новый УправлениеКонфигуратором();

УправлениеКонфигуратором.УстановитьКонтекст("/IBConnectionString" "Srvr=; Ref=''""","Администратор", "ПАРОЛЬ");
ПараметрыЗапуска = УправлениеКонфигуратором.ПолучитьПараметрыЗапуска();
ПараметрыЗапуска.Добавить("/LoadCfg", "путь"); 
УправлениеКонфигуратором.ВыполнитьКоманду(ПараметрыЗапуска);

**Comment by testforgity** [comment]
Я задебажил это все дело и получил такую вот ошибку от моего скрипта: "Слишком много фактических параметров" в строке ПараметрыЗапуска.Добавить("DESIGNER", "/LoadCfg", "путь");
Потом я решил поменять эту строку(сделать как в примере): ПараметрыЗапуска.Добавить("/LoadCfg", "путь");
Но опять получил от своего скрипта ответ-ошибку, с чем это может быть связано?

**Comment by testforgity** [comment]
Я задебажил это все дело и получил такую вот ошибку от моего скрипта: "Слишком много фактических параметров" в строке ПараметрыЗапуска.Добавить("DESIGNER", "/LoadCfg", "путь");
Потом я решил поменять эту строку(сделать как в примере): ПараметрыЗапуска.Добавить("/LoadCfg", "путь");
Но опять получил от своего скрипта ответ-ошибку, с чем это может быть связано?

**Comment by nixel2007** [comment]
Попробуйте использовать готовый метод ЗагрузитьКонфигурациюИзФайла, без пляски с параметрами.

Насколько я помню, параметры запуска - это массив, в него вообще нельзя добавлять несколько элементов одним методом Добавить, надо делать несколько строк.

**Comment by testforgity** [comment]
хм, я заметил такую интересную вещь: если закомментировать всю программу, скрипт все равно откроет 1с, хотя скрипт был точно сохранен после комментирования. Перепроверил через sublime, там тоже все в //. не понимаю что за магия

**Comment by testforgity** [comment]
Если я правильно понимаю, то нужно сделать вот так, но выводит что не задана информационная база. Разве УстановитьКонтекст не задает этот параметр?
УправлениеКонфигуратором = Новый УправлениеКонфигуратором();
УправлениеКонфигуратором.УстановитьКонтекст("/IBConnectionString" "Srvr=; Ref=''""",  "Администратор", "ПАРОЛЬ");
Попытка
УправлениеКонфигуратором.ЗагрузитьКонфигурациюИзФайла("C:/1Cv8.cf", Ложь);
	Сообщить(УправлениеКонфигуратором.ВыводКоманды());
Исключение
	Сообщить(УправлениеКонфигуратором.ВыводКоманды());
КонецПопытки

**Comment by nixel2007** [comment]
Хм. Попробуйте вместо IBConnectionString использовать подключение через /SИмяСервера\ИмяБазы

**Comment by testforgity** [comment]
Спасибо, пролема заключалась именно в этом

**Comment by testforgity** [comment]
а в v8runner есть функция ВыгрузитьКонфигурациюВФайлы?

**Comment by nixel2007** [comment]
Да, есть. Полный список методов можно посмотреть в файле v8runner.os

**Comment by testforgity** [comment]
спасибо большое, нашел
