### ISSUE TITLE
Как узнать используемую версию платформы на сервере?

### ISSUE THREAD

**Issue by testforgity** [oscript-library/v8runner#96]
Хотел узнать версию 1СПредприятия на сервере, а потом уже отталкиваясь от ответа открыть нужную версию на компьютере, подскажите, пожалуйста, какой метод может помочь определить версию, у вас нашел только `ИспользуемаяВерсияПлатформыСтаршеИлиРавна(Знач ТребуемаяВерсияПлатформы)`

**Comment by nixel2007** [comment]
Расскажите причину вопроса - вы пытаетесь подключиться к серверной базе и получаете отлуп о несовпадении версий?

**Comment by EvilBeaver** [comment]
Я решал этот вопрос так. Подключался, ловил исключение, парсил текст и узнавал версию
