### ISSUE TITLE
Как узнать используемую версию платформы на сервере?

### ISSUE THREAD

**Issue by testforgity** [oscript-library/v8runner#97]
Хотел узнать версию 1СПредприятия на сервере, а потом уже отталкиваясь от ответа открыть нужную версию на компьютере, подскажите, пожалуйста, какой метод может помочь определить версию, у вас нашел только 
`ИспользуемаяВерсияПлатформыСтаршеИлиРавна(Знач ТребуемаяВерсияПлатформы)`

**Comment by testforgity** [comment]
И еще вопрос: Как запустить 1с в режиме Конфигуратора?

**Comment by testforgity** [comment]
Да, у меня вылазит сообщение о том, что версии не совпадают

**Comment by EvilBeaver** [comment]
> Как запустить 1с в режиме Конфигуратора?

запустить с помощью чего? Какую задачу вы хотите решить?

**Comment by testforgity** [comment]
я забыл убрать лишнее у вопроса, простите

**Comment by EvilBeaver** [comment]
Но вы не ответили на основной вопрос: какую задачу вы решаете? Мне непонятно с какого конца начинать вам отвечать :)

**Comment by testforgity** [comment]
Есть вот такой скрипт, который выгружает конфигурацию в файлы, хотелось бы не ручками прописывать путь до нужной версии(путь к платформе), а автоматизировать: в зависимости от версии ИБ, ставить путькплатформе в нужную версию
```
#Использовать v8runner

Конфигуратор = Новый УправлениеКонфигуратором();
Конфигуратор.ПутьКПлатформе1С("C:/Program Files (x86)/1cv8/8.3.10.2466/bin/1cv8.exe");
Конфигуратор.УстановитьКонтекст("ИБ",  "Администратор", "ПАРОЛЬ");
Попытка
	Конфигуратор.ВыгрузитьКонфигурациюВФайлы("ПУТЬ", РежимВыгрузкиКонфигурации.Иерархический, Ложь);
	Сообщить(Конфигуратор.ВыводКоманды());
Исключение
	Сообщить(Конфигуратор.ВыводКоманды());
КонецПопытки
```

**Comment by nixel2007** [comment]
Вы, случаем, не [gitsync](https://github.com/oscript-library/gitsync) изобретаете?

**Comment by testforgity** [comment]
именно, хотелось бы не тупо использовать технологию, а разобраться в ней

**Comment by EvilBeaver** [comment]
А что там разбираться, обычный запуск платформы с параметрами...

**Comment by testforgity** [comment]
> А что там разбираться, обычный запуск платформы с параметрами...

я ничего толком не знаю об 1с, поэтому все ооочень сложно идет, учитывая что я пересел с python, c++, где все намного проще(мне так кажется))

**Comment by EvilBeaver** [comment]
С плюсов на 1С? Тут вот какое дело... 1Script это технология, которая сопутствует 1С и добавляет туда плюшки devops и прочей автоматизации. Если не знакомы с 1С, то начинать с 1Script будет немного неверно, имхо. Или вы не занимаетесь 1С, а хотите изучить именно 1Script? можно спрошу какова мотивация?

**Comment by testforgity** [comment]
меня попросил знакомый сделать так, чтобы конфигурация 1с лежала на гите, причем каждый день делать "резервную копию". Все бы ничего, можно батник написать и готово, но я столкнулся с cf файлом, который очень много весит. Дальше начался мой трип по onescript, в частности по вашим работам

**Comment by testforgity** [comment]
уже почти все готово, но вот собрать конфигурацию(cf) из конфигурации(папок) не получается

**Comment by EvilBeaver** [comment]
Если задача выложить в гит, то при чем здесь "собрать"? Если задача собирать из гит - то ваш знакомый хитрит, он явно давно в 1С и знает как найти ребят в опенсорсе (нас), но по какой-то причине не хочет делать это сам (мы просим взамен доработки наших продуктов/фидбек ну и вообще, участие)

Собрать:

``
opm install packman
cd src
packman load-src . && packman make-cf
``

**Comment by testforgity** [comment]
спасибо большое,  просто очень кратко написаны приложения к различным методам(я вас не виню, для вас это просто, а вот для человека не шарящего тяжеловато дается все это)

**Comment by testforgity** [comment]
т.е я чисто теоретически могу кидать вам доработки кода(новые методы, например)?

**Comment by EvilBeaver** [comment]
Конечно. Это называется pull-request и в этом смысл open-source

**Comment by testforgity** [comment]
еще такой вопрос, а какую ide вы используете?

**Comment by EvilBeaver** [comment]
@nixel2007 я боюсь наврать насчет современного положения дел...

Вообще, вот полный туториал: https://infostart.ru/public/791568/

**Comment by nixel2007** [comment]
@EvilBeaver пока что основной IDE все ещё остаётся VSCode

**Comment by testforgity** [comment]
> Если задача выложить в гит, то при чем здесь "собрать"? Если задача собирать из гит - то ваш знакомый хитрит, он явно давно в 1С и знает как найти ребят в опенсорсе (нас), но по какой-то причине не хочет делать это сам (мы просим взамен доработки наших продуктов/фидбек ну и вообще, участие)
> 
> Собрать:
> 
> ```batchfile
> opm install packman
> cd src
> packman load-src . && packman make-cf
> ```

а что если выдает ошибку ключ защиты программы больше не доступен? сталкивались ли вы с этим?

**Comment by nixel2007** [comment]
А лицензия на платформу-то есть? :)

**Comment by testforgity** [comment]
есть

**Comment by testforgity** [comment]
короче, я попробовал через v8runner написать прогу, но только не знаю как запустить от имени администратора, потому что в логах 1с пытается создать(?) файл (скорее всего изменить) в системных папках. Не подскажите как запустить?

**Comment by testforgity** [comment]
#Использовать v8runner

Конфигуратор = Новый УправлениеКонфигуратором();
Конфигуратор.ПутьКПлатформе1С("C:/Program Files (x86)/1cv8/8.3.10.2466/bin/1cv8.exe");
Конфигуратор.СоздатьФайловуюБазу("C:/Users/ляля");
//Конфигуратор.УстановитьКонтекст("/FC:/Users/ляля/Desktop/ttre", "Администратор", "пароль");
Попытка
	Сообщить("Начал загрузку");
	Конфигуратор.ЗагрузитьКонфигурациюИзФайлов("C:/Users/ляля/Desktop/test/last"); //загрузить из файлов
	Сообщить("Закончил загрузку");
	Сообщить("Начал выгрузку");
	Конфигуратор.ВыгрузитьКонфигурациюВФайл("C:/hh"); //выгрузить cf
	Сообщить("Закончил выгрузку");
	Сообщить(Конфигуратор.ВыводКоманды());
Исключение
	Сообщить(Конфигуратор.ВыводКоманды());
КонецПопытки

**Comment by nixel2007** [comment]
Если вы выгружаете в корень диска C, то нужно консоль запускать с правами администратора. В корень диска можно писать только под админом.

**Comment by testforgity** [comment]
> Если вы выгружаете в корень диска C, то нужно консоль запускать с правами администратора. В корень диска можно писать только под админом.

я на рабочий стол кидал, та же фигня

**Comment by testforgity** [comment]
как можно запустить скрипт в VSCode от имени администратора?

**Comment by nixel2007** [comment]
Запустить саму VSCode от имени администратора

**Comment by testforgity** [comment]
Ошибка доступа к файлу 'C:\hh'. 5(0x00000005): Отказано в доступе. 
С чем ошибка связана может быть? вообще все всем пользователям разрешил, кроме системной SysWOW64. И еще вопрос к чему ему там что-то изменять?

**Comment by nixel2007** [comment]
Попробуйте все же имя файла задать с расширением, а не просто hh.

> И еще вопрос к чему ему там что-то изменять?

а как он еще сделает запись на диск, если не будет менять файл? :)

**Comment by testforgity** [comment]
> Попробуйте все же имя файла задать с расширением, а не просто hh.
> 
> > И еще вопрос к чему ему там что-то изменять?
> 
> а как он еще сделает запись на диск, если не будет менять файл? :)

это у меня файл для выгрузки, вот код:
"C:/Program Files (x86)/1cv8/8.3.10.2466/bin/1cv8.exe"  DESIGNER /F"c:\Users\малай\Desktop\test\zzz\v8r_TempDB" /Out "ПУТЬДОТХТ" /DumpCfg "C:/hh"

**Comment by testforgity** [comment]
права админские у пользователя с которого запускаю есть, запускаю скрипт от имени администратора, it's a magic

**Comment by EvilBeaver** [comment]
Что-то вы не то делаете.

**Comment by testforgity** [comment]
можно и так, но итог все равно один "C:/Program Files (x86)/1cv8/8.3.10.2466/bin/1cv8.exe"  DESIGNER /F"c:\Users\малай\Desktop\test\zzz\v8r_TempDB" /Out "ПУТЬДОtxt" /WA+ /DisableStartupMessages /DisableStartupDialogs /DumpCfg "C:/hh"

**Comment by nixel2007** [comment]
> Попробуйте все же имя файла задать с расширением, а не просто hh.

**Comment by testforgity** [comment]
я чуток не понимаю зачем выгружать конфигурацию, например, в тхт файл? или я неправильно понял вас? вы предлагаете, например так: "C:/hh/t.txt"?

**Comment by nixel2007** [comment]
Конфигурация выгружается в файл с расширением cf. Вы указываете путь для этого файла как `C:/hh`, без расширения. я предлагаю попробовать указать `C:/hh.cf`

**Comment by testforgity** [comment]
спасибо большое, понял

**Comment by nixel2007** [comment]
ну и еще как идея - поменять слэш на бэкслэш.
винда же... `¯\_(ツ)_/¯`

**Comment by testforgity** [comment]
> Конфигурация выгружается в файл с расширением cf. Вы указываете путь для этого файла как `C:/hh`, без расширения. я предлагаю попробовать указать `C:/hh.cf`

вот это помогло, спасибо большое еще раз

**Comment by EvilBeaver** [comment]
>> Вы указываете путь для этого файла как C:/hh, без расширения. я предлагаю попробовать указать C:/hh.cf

> вот это помогло, спасибо большое еще раз

А вы точно сварщик?
