### ISSUE TITLE
Нет доступа к папке для выгрузки

### ISSUE THREAD

**Issue by testforgity** [oscript-library/v8runner#98]
Нужно выгрузить конфигурацию в файл, но выдает ошибку: нет прав на запись в папку. Что можно с этим сделать? Папка вроде как открытая на изменения.

**Comment by testforgity** [comment]
И еще, если выгружать в файлЫ, то почему-то не работает автоматическая установка режима выгрузки, приходится прописывать в аргументы процедуры РежимВыгрузкиКонфигурации.Иерархический, хотя по вашему коду должно спокойно подставить автоматом. Магия ¯\_(ツ)_/¯

**Comment by EvilBeaver** [comment]
Если нет прав на запись в папку, значит их нет. Проверьте, под каким пользователем вы запускаете. И точно ли ту папку смотрите, на которую ругается?

**Comment by testforgity** [comment]
я открыл доступ всем для записи и чтения, но ошибка осталась( что еще можно сделать?

**Comment by testforgity** [comment]
Хотел сделать преобразование конфигурации в файлах в конфигурацию в одной папке. Ругается в строчке //выгрузить cf

```
#Использовать v8runner

Конфигуратор = Новый УправлениеКонфигуратором();
Конфигуратор.ПутьКПлатформе1С("C:/Program Files (x86)/1cv8/8.3.10.2466/bin/1cv8.exe");
Конфигуратор.СоздатьФайловуюБазу("ПУТЬ");
Попытка
	Конфигуратор.ЗагрузитьКонфигурациюИзФайлов("ПУТЬ"); //загрузить из xml
	Сообщить("Закончил загрузку");
	Конфигуратор.ВыгрузитьКонфигурациюВФайл("ПУТЬКОТОРЫЙРУГАЕТСЯ"); //выгрузить cf
	Сообщить(Конфигуратор.ВыводКоманды());
Исключение
	Сообщить(Конфигуратор.ВыводКоманды());
КонецПопытки
```

**Comment by EvilBeaver** [comment]
Какое точное значение ПУТЬКОТОРЫЙРУГАЕТСЯ и полный текст ошибки, выдаваемый 1Скрипт?

**Comment by testforgity** [comment]
Ошибка доступа к файлу 'C:\Users\test\Desktop\hh'. 5(0x00000005): Отказано в доступе.
