### ISSUE TITLE
Можете добавить?

### ISSUE THREAD

**Issue by testforgity** [oscript-library/v8runner#99]
Хочу предложить исправление в v8runner.os. Добавить /AppAutoCheckVersion –подбирает нужную версию платформы для каждой запускаемой информационной базы;

**Comment by testforgity** [comment]
это упростит использование библиотеки

**Comment by EvilBeaver** [comment]
А сам?

**Comment by testforgity** [comment]
могу попробовать, только я этот ЯП увидел пару дней назад и за 100% правильность не ручаюсь

**Comment by EvilBeaver** [comment]
Это язык 1С. 1С вы тоже увидели недавно?
